variables

diff --git a/13-installation b/13-installation
--- a/13-installation
+++ b/13-installation
@@ -7,29 +7,20 @@ if [ $USERID -ne 0 ]; then
     exit 1 # failure is other than 0
 fi
 
-yum install mysql -y
+VALIDATE(){ # functions receive inputs through args just like shell script args
+    if [ $1 -ne 0 ]; then
+        echo "ERROR:: Installing $2 is failure"
+        exit 1
+    else
+        echo "Installing $2 is SUCCESS"
+    fi
+}
 
-if [ $? -ne 0 ]; then
-    echo "ERROR:: Installing MYSQL is failure"
-    exit 1
-else
-    echo "Installing MYSQL is SUCCESS"
-fi
+yum install mysql -y
+VALIDATE $? "MYSQL"
 
 yum install nginx -y
-
-if [ $? -ne 0 ]; then
-    echo "ERROR:: Installing Nginx is failure"
-    exit 1
-else
-    echo "Installing Nginx is SUCCESS"
-fi
+VALIDATE$? "Nginx"
 
 dnf install mongodb-mongosh -y
-
-if [ $? -ne 0 ]; then
-    echo "ERROR:: Installing mongodb-mongosh is failure"
-    exit 1
-else
-    echo "Installing mongodb-mongosh is SUCCESS"
-fi
+VALIDATE $? "mongosh"
